import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import HeaderNav from "../components/HeaderNav";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark`}>
        <Providers>
          <HeaderNav />
          <div className="flex flex-row items-center justify-center md:h-[calc(100vh-64px)] p-24">
            {children}
            <ToastContainer position="bottom-right" />
          </div>
        </Providers>
      </body>
    </html>
  );
}
