import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import HeaderNav from "./ui/HeaderNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark`}>
        <Providers>
          <HeaderNav />
          <div className="flex md:h-[calc(100vh-64px)] items-center justify-between p-24">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
